default: &default
  adapter: postgresql
  encoding: utf8
  username: sandeshsoni
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: snappea_dev

test:
  <<: *default
  database: snappea_test